@startuml
public class Ea3_6UsoExcepciones {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        int numeoi = 0;
        while(true){
           try{
         Scanner captu = new Scanner(System.in);
         
            System.out.println("Introduce un n√∫mero");
            numeoi= captu.nextInt();
            break;
           }catch(InputMismatchException e){
               System.out.println("El valor no es valido, vuelve a intentarlo");
           }
           }
        System.out.println("El valor capturado es = " + numeoi);
        }
@enduml
